import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import { Poppins } from 'next/font/google';
import { Inter } from "next/font/google";
import NextTopLoader from 'nextjs-toploader';

import "./globals.css";
import ClientProvider from "@/Redux/ClientProvider";

const manrope = Manrope({ subsets: ["latin"], variable: '--font-manrope' });
const inter= Inter({ subsets: ["latin"], variable: '--font-inter' });
const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${manrope.variable} ${poppins.variable} ${inter.variable}`}>

      <body >
      <NextTopLoader height={4}  color="#3393ff"   
  initialPosition={0.08}
  crawlSpeed={200}
  
  crawl={true}
  easing="ease"
  speed={200}
  shadow="0 0 10px #2299DD,0 0 5px #2299DD"
  zIndex={1600}
  showSpinner={false}
  showAtBottom={false}/>

     <ClientProvider>
      
      {children}
      </ClientProvider> 


      
      </body>
    </html>
  );
}
