import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import { Poppins } from 'next/font/google';
import { Inter } from "next/font/google";

import "./globals.css";
import ClientProvider from "@/Redux/ClientProvider";

const manrope = Manrope({ subsets: ["latin"], variable: '--font-manrope' });
const inter= Inter({ subsets: ["latin"], variable: '--font-inter' });
const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${manrope.variable} ${poppins.variable} ${inter.variable}`}>

      <body >
     <ClientProvider>
      
      {children}
      </ClientProvider> 
      
      </body>
    </html>
  );
}
