import {
  MilkImg,
  Bread,
  egg,
  Cheese,
  Rice,
  Butter,
  Banana,
  Peach,
  Spinach,
  Strawberry,
  Apple,
  Orange,
  Potato,
  Carrot,
} from "@/assets";

export const products = [
  {
    name: "Dairy",
    quantity: "1 liter",
    imageUrl: MilkImg,
    isSelected: false,
    className: "bg-customCart1",
  },
  {
    name: "Grocery",
    quantity: "500 grams",
    imageUrl: Bread,
    isSelected: false,
    className: "bg-customCart2",
  },
  {
    name: "Meat",
    quantity: "12 eggs",
    imageUrl: egg,
    isSelected: false,
    className: "bg-customCart3",
  },
  {
    name: "Cheese",
    quantity: "200 grams",
    imageUrl: Cheese,
    isSelected: false,
    className: "bg-customCart4",
  },
  {
    name: "Butter",
    quantity: "250 grams",
    imageUrl: Butter,
    isSelected: false,
    className: "bg-customCart5",
  },
  {
    name: "Rice",
    quantity: "1 kilogram",
    imageUrl: Rice,
    isSelected: false,
    className: "bg-customCart6",
  },
  {
    name: "Bananas",
    quantity: "1 kilogram",
    imageUrl: Banana,
    isSelected: false,
    className: "bg-customCart7",
  },
  {
    name: "Peach",
    quantity: "500 grams",
    imageUrl: Peach,
    isSelected: false,
    className: "bg-customCart8",
  },
  {
    name: "Vegetables",
    quantity: "500 grams",
    imageUrl: Spinach,
    isSelected: false,
    className: "bg-customCart9",
  },
  {
    name: "Strawberry",
    quantity: "250 grams",
    imageUrl: Strawberry,
    isSelected: false,
    className: "bg-customCart10",
  },
  {
    name: "Apple",
    quantity: "100 grams",
    imageUrl: Apple,
    isSelected: false,
    className: "bg-customCart11",
  },
  {
    name: "Orange",
    quantity: "200 grams",
    imageUrl: Orange,
    isSelected: false,
    className: "bg-customCart12",
  },
  {
    name: "Potato",
    quantity: "500 grams",
    imageUrl: Potato,
    isSelected: false,
    className: "bg-customCart13",
  },
  {
    name: "Carrot",
    quantity: "100 Items",
    imageUrl: Carrot,
    isSelected: false,
    className: "bg-customCart14",
  },
];
export const colorsList = [
 "customCart1",
  "customCart2",
  "customCart3",
  "customCart4",
  "customCart5",
  "customCart6",
  "customCart7",
  "customCart8",
  "customCart9",
  "customCart10",
  "customCart11",
  "customCart12",
  "customCart13",
  "customCart14",];
